### ISSUE TITLE
Existing running instance of PoECustomSoundtrack does not play menu music after restarting game

### ISSUE THREAD

**Issue by philanderadriaan** [jareddr/PoECustomSoundtrack#10]
Fix here:
https://www.dropbox.com/s/wc7okn9rrm58m3t/poeCustomSoundtrack.js

Now if we restart the game, we don't need to restart PoECustomSoundtrack anymore for menu music to work.

![Diff](https://user-images.githubusercontent.com/5098967/152664528-a1a75e3b-8e71-457c-833b-a1442da76b5b.PNG)

**Comment by jareddr** [comment]
I didn't end up using your solution, but I think I may have fixed the problem.  Try out the latest push and let me know.

I think there is something wrong with the auto-update.  Not sure how to fix that, so you'll have to download the newest installer.

**Comment by philanderadriaan** [comment]
@jareddr latest push works fine. Thanks for keeping this tool active.
