### ISSUE TITLE
v1.5 release version unable to select PoE directory and Soundtrack file

### ISSUE THREAD

**Issue by philanderadriaan** [jareddr/PoECustomSoundtrack#11]
Looks like the v1.5 release introduced a bug from the below commit, where we're unable to select PoE directory and soundtrack file.

https://github.com/jareddr/PoECustomSoundtrack/commit/21f10b5062bb6044e1cf2be075451f0c1faa4dcb

Reverting changes from that commit and then doing a npm install seem to get it working again.

**Comment by philanderadriaan** [comment]
I managed to narrow down the problem to the electron version in package.json. I reverted it from ~13.2.3 to ~2.0.8, then do a npm install, then it's working again.

![Capture](https://user-images.githubusercontent.com/5098967/153766123-e7345e50-eada-455f-8dff-c07893c03c1c.PNG)

**Comment by jareddr** [comment]
oh thanks for finding this, ill see if I can get the patch out today

**Comment by philanderadriaan** [comment]
Yes I tried it with the release installer.

Installing v1.5 I'm unable to change soundtrack files.

Installing v1.4.4 I'm able to change soundtrack files, then when I update to v1.5 using the updater and I'm unable to change soundtrack files again.

**Comment by jareddr** [comment]
Ah yeah sorry I figured it out after I wrote you.  There was an api change in electron for the `showOpenDialog` function.  The old one took a callback function and the new one returns a promise, so the fix looks like this 

```
// handle file select dialog
function loadLogFile() {
  dialog.showOpenDialog({
    title: 'Locate PoE Directory',
    properties: ['openDirectory'],
  }).then ( results =>{
    ipcRenderer.send('setPoePath', results.filePaths)
  });
}
```

**Comment by philanderadriaan** [comment]
Awesome
