### ISSUE TITLE
Default Template

### ISSUE THREAD

**Issue by brswattt** [jareddr/PoECustomSoundtrack#24]
Hi,

Is there a default .json template for people who want to lets say, replace only a couple of tracks (the lionseye/forest encampment) and keep everything else default?

**Comment by jareddr** [comment]
There is a `.soundtrack` file that gets created when you first launch the app.  I'm now just realizing that its actually hard to find that file if you use the installer.  I don't know what directory it gets dropped in.  I'm digging around now.

A question though about what you're trying to do... when you say 'Default' do you mean 'default' path of exile music, or default diablo2 tracks that I've already picked out for each zone?.

If you want to keep the default PoE music, it would be... tricky.

**Comment by jareddr** [comment]
Here's the default template: https://pastebin.com/raw/PnfBehk5

Save it as `whatever.soundtrack` and then load it up in the app to make sure it works.  Then you can edit it with a text editor.

To add a new song you'd to to the 'tracks' section and create a new record

```
                 {
			"name": "rogue_encampment",
			"location": "https://www.youtube.com/watch?v=t1Zf9w--VhM"
		},
                 {
			"name": "my_new_song",
			"location": "https://www.youtube.com/watch?v=t1Zf9w--VhM"
		},
```

Then you can map that new song to a zone in the 'map' section below. 

```
	"map": {
		"login": "intro",
		"Lioneye's Watch": "my_new_songt",
		"The Twilight Strand": "wild",
		"The Coast": "wild",
```
So if you want to change the music for Lioneye's youd just change the keyword 'rogue_encampment' to match one of the songs in the list at the top of the file, like, 'my_new_song'

I've been meaning to update this app to have a soundtrack editor built into it, but haven't found the time.

**Comment by brswattt** [comment]
I found that .soundtrack file, but it had a bunch of entries and replaced options already for said areas, didn't know if there was some default template without them filled in. Didn't know how exactly this worked in regards to the in-game music. Yes, keep everything default meaning the default path of exile music, not the default diablo 2 tracks. Reason: I like the old closed beta act 1 / 2 town songs better than the new ones, lol

**Comment by jareddr** [comment]
Aha yeah... that's super tricky.  In order for this app to work well you generally want to have the path of exile music OFF.  It's a total replacement.  Otherwise on the zones that you're trying to replace you'd get both songs playing at once.

The one thing you could do, but it would take a ton of work... would be to find youtube videos for the entire path of exile soundtrack and remap it to zones.  

Then you could, for instance, replace the Lioneye's with the original track from 5 years ago or whenever they changed it.  All of the music would play through this app.  It would be a big undertaking though.

**Comment by jareddr** [comment]
It looks like all the poe soundtrack files are already up as individual youtube videos, so it looks pretty easy to pull this off.

https://www.youtube.com/watch?v=ypUJ5cRsXCE&list=PLs2gPxL93WG2SOfkNpx3fNcIfENggEINX&index=55

**Comment by brswattt** [comment]
Gotcha. Thanks for the info. I'll attempt this if I wanna pursue.
