### ISSUE TITLE
Zone List update

### ISSUE THREAD

**Issue by vidjunkie** [jareddr/PoECustomSoundtrack#5]
Where can I get an updated list of zones to trigger tracks to play? Or how can I find it myself?

**Comment by jareddr** [comment]
It's whatever gets printed out in chat when you enter a new area "You have
entered The Docks".

The wiki has a list of all the maps:
https://pathofexile.fandom.com/wiki/List_of_maps

You could figure out which ones are missing and fill them in.

If you want to submit a pull request, I'll merge the changes in

**Comment by vidjunkie** [comment]
Sounds good. I believe it is mainly the newer hideouts that are missing. I'll get a list going and post in pull requests when I'm done.

**Comment by vidjunkie** [comment]
After some seraching, I have no idea how to make a pull request. Here's the zones I found missing

Innocent Hideout
Crucible Hideout
Glacial Expanse Hideout
All at Sea Hideout
Vast Plains Hideout
Eternal Wasteland Hideout
Endless Sands Hideout
Boundless Skies Hideout
Urban Sprawl Hideout
Infinite Abyss Hideout
Thaumaturigcal Hideout
Champion's Hideout
Ravenous Hideout
Morbid Hideout
Furious Hideout
Void Hideout
Celestial Nebula Hideout
Indomitable Hideout
Towering Hideout
Corrupted Hideout
Eclipsed Hideout
Glimmerwood Hideout
Shaped Hideout

Acid Caverns
Bramble Valley
Cold River
Crater
Crimson Township
Dry Sea
Forbidden Woods
Forking River
Foundry Map
Frozen Cabins Map
Fungal Hollow Map
Glacier
Grave Trough Map
Primordial Blocks
Silo

(Remove Acid Lakes)
(Remove Gorge)
(Remove Springs)
(Remove Torture Chamber)
(Remove Tribunal)

**Comment by vidjunkie** [comment]
Also the login trigger only works about 1in 10 times or not at all.

**Comment by jareddr** [comment]
Yeah I've seen that... I'm not sure what's up.  I've manually watched the
logs and the line its looking for always gets printed out.  Its almost like
my program is missing every X log lines or something.

**Comment by jareddr** [comment]
Also, thanks for the zone list!

You can probably edit the soundtrack file yourself, it's not too bad.

Here is a quick run through of the soundtrack you would need to edit:
https://www.youtube.com/watch?v=DyfBy1K1Y1s&t=2m31s

**Comment by vidjunkie** [comment]
No Problem. Thanks for the help! I've started editing the list in a new save. Cheers!
