### ISSUE TITLE
Update new zones

### ISSUE THREAD

**Issue by philanderadriaan** [jareddr/PoECustomSoundtrack#6]
I have updated new zones up to ultimatum. If you can give me access I will help update the zones for every league.

**Comment by jareddr** [comment]
Hey! Send me the file and I'll update the app

**Comment by philanderadriaan** [comment]
Updated for Expedition.

https://www.dropbox.com/s/vwoxpnd4e2irs9k/defaults.js?dl=1

**Comment by jareddr** [comment]
Thanks! I'll test this out tonight and see if I can publish a new release

**Comment by jareddr** [comment]
Published the update
