### ISSUE TITLE
Disconnecting to menu does not play menu music

### ISSUE THREAD

**Issue by philanderadriaan** [jareddr/PoECustomSoundtrack#8]
Partial fix here:
https://www.dropbox.com/s/wc7okn9rrm58m3t/poeCustomSoundtrack.js

Menu music will now play when selecting "Exit to character selection" or during unexpected disconnection. Selecting "Exit to log in screen" still doesn't work.

Diff:
https://i.imgur.com/P7Aq9Ob.png

**Comment by jareddr** [comment]
Thanks, updated!
